### ISSUE TITLE
Implement command

### ISSUE THREAD

**Issue by kamijin-fanta** [kamijin-fanta/sakuraio-cli#1]
- module
  - [x] list
  - [x] show
  - [x] add
- project
  - [x] list
  - [x] show
  - [x] add
  - [x] remove
- service
  - [x] list
  - [x] show
  - [x] remove
  - outgoingwebhook
  - incoming-webhook
  - websocket
    - [x] listen
  - datastore
    - [x] messages
    - [x] channels

**Comment by whywaita** [comment]
Complete!
